@startuml aggiornaDatiUtenti
Utente->PrestitoFilm: main()
PrestitoFilm->PrestitoFilm: aggiornaDatiUtenti(utenteMain)
Utente->PrestitoFilm: Richiedi aggiornamento dei dati utente
PrestitoFilm->Utente: Restituisci informazioni attuali dell'utente
Utente->PrestitoFilm: Stampa informazioni attuali dell'utente e dei film presi in prestito
Utente->PrestitoFilm: Fornisci scelta di conferma o annullamento aggiornamento dati
PrestitoFilm->Utente: Se scelta è conferma, aggiorna i dati dell'utente
Utente->PrestitoFilm: Altre interazioni con l'applicazione (menu, input, ecc.)
@enduml