@startuml caricamentoUtenti
Utente->PrestitoFilm: main()
PrestitoFilm->PrestitoFilm: caricamentoUtenti(elencoUtenti)
PrestitoFilm->File: Apri "ElencoUtenti.txt"
File->PrestitoFilm: Leggi riga del file
PrestitoFilm->Utente: Creazione istanza di Utente
Utente->PrestitoFilm: Restituisci istanza di Utente
PrestitoFilm->PrestitoFilm: Aggiungi Utente all'elencoUtenti
PrestitoFilm->File: Chiudi file
@enduml
