@startuml cercaGenere
Utente->PrestitoFilm: main()
PrestitoFilm->PrestitoFilm: cercaGenere(elencoFilm)
Utente->PrestitoFilm: Fornisci il genere da cercare
PrestitoFilm->Utente: Verifica se l'utente ha film in prestito
Utente->PrestitoFilm: Stampa l'elenco dei generi disponibili
Utente->PrestitoFilm: Seleziona un genere
PrestitoFilm->Film: Verifica se il genere corrisponde a un film nell'elenco
Utente->PrestitoFilm: Stampa informazioni sui film corrispondenti
Utente->PrestitoFilm: Altre interazioni...
@enduml